### ISSUE TITLE
Sharp module error after running gatsby develop

### ISSUE THREAD

**Issue by codewithjalaj** [pranavmalvawala/pranavmalvawala.com#1]
I cloned the original repo (taniarascia.com) on my local machine. After installing all dependencies when I run `gatsby develop` its giving me an error saying, 
```
Something went wrong installing the "sharp" module

The specified procedure could not be found.
\\?\J:\Stuff\mysite.com\node_modules\gatsby-plugin-manifest\node_modules\sh
arp\build\Release\sharp.node

- Remove the "node_modules/sharp" directory, run "npm install" and look for erro
rs
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/s
table/install/
- Search for this error at https://github.com/lovell/sharp/issues


``` 
I tried removing the folder and running `npm install` but same error.
As you have successfully cloned the repo earlier. I am hoping you would help me fixing it.

**Comment by pranavmalvawala** [comment]
Hi @codewithjalaj  I've no idea what does that have to do with creating an issue on my repo, seems completely unrelated.  But still from what I know this is not the error you should be getting, the main error is related to unsuccessful execution of graphql queries. The reason for that is we do not have access to content folder anymore

**Comment by codewithjalaj** [comment]
Right after i fixed the sharp module error i got the unsuccessful execution error. This can be easily fixed. Thanks!
